### ISSUE TITLE
RHEL/CentOS 7 Package Support?

### ISSUE THREAD

**Issue by jeteokeeffe** [sensu/sensu-build#89] opened 2014-08-18 04:58 UTC
Is there any plans to support RHEL/CentOS 7 package? Anything I can help with?

**Comment by mcortinas** [comment] 2015-01-16 16:27
+1

**Comment by mateodelnorte** [comment] 2015-02-12 17:39
+1 is this merged and deployed? 

what's the current workaround for CentOS 7 users if it's not yet live?

**Comment by nathwill** [comment] 2015-02-12 18:22
@mateodelnorte we're just hard-coding the EL 6 repo

```ruby
# Use EL 6 Repo on EL 7
# TODO: remove when Sensu publishes EL 7 packages
if node.platform_family?('rhel') && node.platform_version.to_f >= 7.0
  rewind yum_repository: 'sensu' do
    url "http://repos.sensuapp.org/yum/el/6/$basearch/"
  end
end
```

**Comment by mateodelnorte** [comment] 2015-02-12 18:37
What file needs to be modified to do that? 

Doesn't someone need to just publish the new build? Looks like the 7 build was merged in #99.

The entire community shouldn't be doing a hack, when hopefully someone can just run one command and publish. ...unless I'm missing something.

**Comment by nathwill** [comment] 2015-02-12 18:43
@mateodelnorte that's from our Chef CM scripts; we added before the EL 7 support got merged into the build-scripts, and are definitely planning on ripping it out as soon as the EL 7 repo is live. In the meantime, the EL 6 packages are working just fine.

**Comment by mateodelnorte** [comment] 2015-02-12 18:55
got it. I'm using ansible, so I'll have to check out how to specify the yum baseurl. thx.

**Comment by FlorinAndrei** [comment] 2015-03-09 19:56
Would be very nice if this was fixed. It's been a while since the issue was opened, and v7 is being used more and more.

**Comment by bdejong** [comment] 2015-03-17 16:59
+1

**Comment by charliedrage** [comment] 2015-04-02 14:16
+1

**Comment by davidstrauss** [comment] 2015-04-07 01:15
+1

**Comment by FlorinAndrei** [comment] 2015-04-10 22:03
It appears that now that Sensu's public yum repo is correctly configured for EL7.

On CentOS 7, I've created this file:

```
# cat /etc/yum.repos.d/sensu.repo 
[sensu]
name=sensu-main
baseurl=http://repos.sensuapp.org/yum/el/$releasever/$basearch/
gpgcheck=0
enabled=1
```

And then trying to do "yum install sensu" works just fine.

The issue appears to be fixed.

**Comment by gdhbashton** [comment] 2015-04-13 08:34
It's true that a symlink now exists so that `http://repos.sensuapp.org/yum/el6/` and `http://repos.sensuapp.org/yum/el7` point to the same packages so that packages install and function, however they are relying on legacy init.d scripts rather than using systemd unit files. I'll attempt a PR for that and link to it here.

**Comment by johnpatcher** [comment] 2015-05-08 17:15
@gdhbashton Any news on the native systemd support? Would like to see that :).

**Comment by gdhbashton** [comment] 2015-05-08 18:22
Hi John - afraid not. Paying customers and moving house are taking rather a lot of precedence. My own unit files are in a far shoddier state than I'd like (i.e. they work enough for my use, but are not generic enough for public consumption)

**Comment by calebhailey** [comment] 2015-05-08 18:41
Hello all, it seems to me that the original issue - which required a workaround to even get the packages to install on RHEL/CentOS 7 - has been resolved and confirmed by a few folks in this thread. Perhaps we should close this and create a new issue for the systemd support? Any objections? 

@gdhbashton do you want to create a new issue for discussion/input from others? 

#monitoringlove :smile:

**Comment by jhmartin** [comment] 2015-07-27 20:24
https://github.com/sensu/sensu-build/blob/master/runit_scripts/sensu-ctl.rb#L140 makes assumptions that it should use /etc/inittab for startup if not on EL6, which is ignored by systemd on centos7.

**Comment by jrwesolo** [comment] 2015-11-17 17:06
I believe https://github.com/sensu/sensu-build/pull/122 is attempting to solve this.

**Comment by cwjohnston** [comment] 2016-10-13 19:18
We are currently working to migrate Sensu's build and release process away from the tools in this repo to a toolchain using Chef's Omnibus (see #184). 

As part of this process we are planning to drop support for upstart and runit to focus on sysv and systemd as the officially supported service managers (see https://github.com/sensu/sensu-omnibus/issues/34).

I believe changes described here will not be necessary for running omnibus builds on Centos 7 and other platforms with systemd as the init system. I've added this PR to the 0.27 milestone to reflect that it is superseded by the switch to omnibus builds which will be used to generate Sensu 0.27 packages.

**Closed by cwjohnston** 2016-10-13 19:18 UTC
Labels: Feature
